### ISSUE TITLE
02/25/2015

### ISSUE THREAD

**Issue by marsgatchalian** [marsgatchalian/Hello#1]
10:45PM: test..

**Comment by ericjandale** [comment]
10:46: test.. i think pwede na muna to bae. huhu..

**Comment by ericjandale** [comment]
10:50 --manual kong nilalagay yung time... :)

**Comment by marsgatchalian** [comment]
babyyy

**Comment by marsgatchalian** [comment]
zz :(

**Comment by marsgatchalian** [comment]
late na kami nakarating :( hay ano ba to :(

**Comment by marsgatchalian** [comment]
bat di ka nagcomment dito :( di ko nabasa reply mo sa fb.

**Comment by marsgatchalian** [comment]
zz

**Comment by ericjandale** [comment]
hahaha

**Comment by ericjandale** [comment]
kauwi ko lang e

**Comment by marsgatchalian** [comment]
hi ;)

**Comment by ericjandale** [comment]
Pa edsa palang 😂😂

**Comment by marsgatchalian** [comment]
hi bae sorry ngayn ko lang nakita haha :*

**Comment by marsgatchalian** [comment]
ingat ka bae :*

**Comment by ericjandale** [comment]
:p

**Comment by marsgatchalian** [comment]
yuuun pwede pala ko punta whaha. hi bae :dancer:

**Comment by ericjandale** [comment]
Haha oo kaso antayin pa sila. Market muna tayo

**Comment by marsgatchalian** [comment]
sige po :* :* :*

**Comment by marsgatchalian** [comment]
ohayoo bae :)

**Comment by ericjandale** [comment]
ohayoo haha :)) z :* kagising lang

**Comment by marsgatchalian** [comment]
hi babyyy haha what time ka sleep? mag bfast ka naaa~

**Comment by marsgatchalian** [comment]
:* :*

**Comment by ericjandale** [comment]
12:30 ata? :)))

**Comment by marsgatchalian** [comment]
haha nooooooo puyat nanaman siyaaaaaa......

**Comment by marsgatchalian** [comment]
mahirap ba dito bae? haha i mean sa phone version? dito kaso parang fb lang e.

**Comment by ericjandale** [comment]
di naman haha :*

**Comment by marsgatchalian** [comment]
ahh wala lang notif? haha

**Comment by ericjandale** [comment]
haha :)) oo pero di na kelangan refresh

**Comment by marsgatchalian** [comment]
ahhh nicee haha :D :D

**Comment by marsgatchalian** [comment]
meeting kami 9:45 pero mga 5 mins lang yun haahah

**Comment by ericjandale** [comment]
ah haha sige take care :*

**Comment by marsgatchalian** [comment]
wait lang haha

**Comment by ericjandale** [comment]
ano yung "okay i wont talk to youuuu"? ha?

**Comment by marsgatchalian** [comment]
si tin haha kainis kasee

**Comment by marsgatchalian** [comment]
done na meeting haha

**Comment by ericjandale** [comment]
tin?

**Comment by marsgatchalian** [comment]
check mo pa messenger ko  isang tanong isang sagot kasi haha z

**Comment by marsgatchalian** [comment]
christine haha z

**Comment by marsgatchalian** [comment]
ay inalis ko pala yun haha kung gusto mo check punta ka nalang sa profile niya tapos click mo yung message ahaha. tapos pumunta na siya pcc di nag ayaaa. eh lagi kami yung magkasama dun. zz

**Comment by ericjandale** [comment]
hahaha zz

**Comment by marsgatchalian** [comment]
bae delete ko na yung iba para di masyado humaba ah haha

**Comment by ericjandale** [comment]
sige haha

**Comment by marsgatchalian** [comment]
hi, okay na haha

**Comment by marsgatchalian** [comment]
baeee

**Comment by ericjandale** [comment]
Hi, pano ka nakakapagtxt haaa

**Comment by marsgatchalian** [comment]
wala kong bhoxzsh. haha mayang afternoon pa :D :dancers:

**Comment by ericjandale** [comment]
Ah hahaha z edi pwede fb? :))

**Comment by marsgatchalian** [comment]
no padin. haha :D

**Comment by ericjandale** [comment]
Why? Haha z

**Comment by marsgatchalian** [comment]
sa sysad yun makita eh haha

**Comment by ericjandale** [comment]
Sysad? Haha

**Comment by marsgatchalian** [comment]
oo basta parang IT haha

**Comment by ericjandale** [comment]
Haha z

**Comment by marsgatchalian** [comment]
haha gawa mo na?

**Comment by ericjandale** [comment]
wala haha sims z

**Comment by marsgatchalian** [comment]
ahh haha :D :* :* poprogram ako bae :*

**Comment by marsgatchalian** [comment]
kaya late reply haha

**Comment by ericjandale** [comment]
ah ahaha :P :P :P no

**Comment by marsgatchalian** [comment]
haha sorry na bae :*

**Comment by ericjandale** [comment]
haha ona, ano bfast mo?

**Comment by marsgatchalian** [comment]
hahaha spag uli haha di nga nakapag dinner e :(

**Comment by ericjandale** [comment]
haha yaan mo na yun :*

**Comment by marsgatchalian** [comment]
haha opo:* :*

**Comment by ericjandale** [comment]
haha :* :* grabe clear ng clear? :))

**Comment by marsgatchalian** [comment]
haha oo para di safe . :D lunch na bae :D :*

**Comment by ericjandale** [comment]
di kana nagtxt  haha z

**Comment by ericjandale** [comment]
...

**Comment by marsgatchalian** [comment]
baebae :* ano na eat mo?

**Comment by marsgatchalian** [comment]
sorry bae nag brush na.. lam mo naman haha z

**Comment by marsgatchalian** [comment]
saka inaayos ko ung program huhu T_T

**Comment by ericjandale** [comment]
wusuuuuuu hhaha, wala hotdog lang

**Comment by marsgatchalian** [comment]
ahh haha zzz :* :*

**Comment by marsgatchalian** [comment]
ngayon ko lang naayos after so many hours T_T

**Comment by ericjandale** [comment]
haha :* ayos lang yan

**Comment by marsgatchalian** [comment]
hi bae. coffee break namins :dancers:

**Comment by ericjandale** [comment]
haha di ka naman rereply sa fb z

**Comment by marsgatchalian** [comment]
huhu naaadik ako mag code bae sorry huuhu

**Comment by ericjandale** [comment]
:( :P

**Comment by marsgatchalian** [comment]
hi baee huhu

**Comment by marsgatchalian** [comment]
sorry bae :(

**Comment by marsgatchalian** [comment]
hi bae :*

**Comment by ericjandale** [comment]
Hi :*

**Comment by marsgatchalian** [comment]
kumain ka na baby? :*

**Comment by ericjandale** [comment]
Di pa :)) z

**Comment by marsgatchalian** [comment]
eat na abaaaa :D :D :D :* :*

**Comment by ericjandale** [comment]
Maya na, brunch ko nalang :)) :*

**Comment by marsgatchalian** [comment]
EHHHHHHHHHHHHHHHHHHHHHHHHHHHH >:p (mad)

**Comment by ericjandale** [comment]
Ehhhhhh sarap higa e haha z

**Comment by marsgatchalian** [comment]
noooo bangooonnnnnnn (mad)

**Comment by marsgatchalian** [comment]
bae di ka na reps haha

**Comment by ericjandale** [comment]
Hi bae sorry di na nakareply haha z :* :*

**Comment by marsgatchalian** [comment]
hi bae gawa mo ba? haha

**Comment by marsgatchalian** [comment]
:* :*

**Comment by ericjandale** [comment]
Nunuod two and a half men :* :*

**Comment by marsgatchalian** [comment]
ahh haha sige. :D nasira pinoprogram ko haha ayusin ko muna :) :*

**Comment by ericjandale** [comment]
Haha sige po goodluck :* :* :*

**Comment by marsgatchalian** [comment]
thanks bae :* :*

**Comment by marsgatchalian** [comment]
okay na pala daw net baby :* pinalitan modem :)

**Comment by marsgatchalian** [comment]
helloooo~ :+1:

**Comment by ericjandale** [comment]
Hi haha naliligo me

**Comment by marsgatchalian** [comment]
ewwwwwwww hahaha

**Comment by ericjandale** [comment]
Anong ewww dun? Hahaha z

**Comment by marsgatchalian** [comment]
haha baho :dash:

**Comment by marsgatchalian** [comment]
hi baeee

**Comment by ericjandale** [comment]
Hi haha 😘😘😘😘

**Comment by marsgatchalian** [comment]
hahaha :* :* :* :* gawa mo bae?

**Comment by ericjandale** [comment]
Haha wala nuod lang 😘😘 kaw?

**Comment by marsgatchalian** [comment]
program. nakakamatay T_T

**Comment by ericjandale** [comment]
Haha z bat naman?

**Comment by marsgatchalian** [comment]
hirap T_T

**Comment by marsgatchalian** [comment]
pero okay lang. sana walang deadline. yun lang nman prob ko kasi may exam pa ko. pero okay lang ako kahit mahirap :)

**Comment by ericjandale** [comment]
Ah haha :* para san ba yan ginagawa mo?

**Comment by marsgatchalian** [comment]
para masanay haha zz T_T kailangan to kasi parang project ko na to e :(

**Comment by marsgatchalian** [comment]
hello :smile:

**Comment by ericjandale** [comment]
Hi haha 😂

**Comment by marsgatchalian** [comment]
busy day adain (mej) dahill sa coding haha sana gumana na  T_T :cry:

**Comment by marsgatchalian** [comment]
again*

**Comment by ericjandale** [comment]
Hahahays lag

**Comment by marsgatchalian** [comment]
bae namove llunch namin 1pm-2pm wala pa ung caterer ehh

**Comment by marsgatchalian** [comment]
bae uwi ako mabae uwi ako maaga

**Comment by marsgatchalian** [comment]
... ohayoooouu :)

**Comment by ericjandale** [comment]
Hi hahah

**Comment by ericjandale** [comment]
Hayyyyy
